name: Build Release

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    uses: ./.github/workflows/build_and_upload.yml
    with:
      isRelease: true
      shouldUpload: true
    secrets: inherit